### ISSUE TITLE
[PE-D][Tester E] Misspelt 'vomiting' as 'vomitting'

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-3/tp#114]
Related to the same command in issue #2, there is spelling error in "radd d/28-02-2024 2030 r/Patient experienced vomitting". Minor issue but you might want to change that :) 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: eugenelmj/ped#3

**Comment by EiffelLKF** [comment]
Will update in UG
