### ISSUE TITLE
[PE-D][Tester A] Accepting of long phone number lengths

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-3/tp#124]
It is a deliberate attempt to include a phone number that is of long length. It shouldn't be the case where the phone number length be of length greater than 8 or 11 (if we are going to +65)

![Screenshot 2022-10-28 at 4.29.25 PM.png](https://raw.githubusercontent.com/AshiqurRah/ped/main/files/91a9ce0d-ac03-43f9-8934-b38cccf13af6.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: AshiqurRah/ped#2

**Comment by EiffelLKF** [comment]
Will limit to up to 15 digits (longest international phone number)
