### ISSUE TITLE
[PE-D][Tester C] Apptcl command resets the list of patients

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-3/tp#128]
### Description

`apptcl` resets the list of patients and does not look like the intended behavior.

### Steps to recreate bug
1. Open a new instance of the application
2. Enter `find Irfan Roy`
3. Enter `apptcl 1`

![image.png](https://raw.githubusercontent.com/changjy44/ped/main/files/0e29da49-e511-4d76-982f-7ee56a518d13.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: changjy44/ped#4

**Comment by LJXSean** [comment]
This command follows the consistent behaviour of the other patient list commands like edit, that returns to the main patient list after execution.

**Comment by EiffelLKF** [comment]
Will update UG
