### ISSUE TITLE
[PE-D][Tester A] Specificity of error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-3/tp#132]
Error message is shown but user will not be sure what is the error due to like in this case. Error message should also show what could be done to correct this input error

![Screenshot 2022-10-28 at 4.44.04 PM.png](https://raw.githubusercontent.com/AshiqurRah/ped/main/files/e5a02fb8-f4a9-453c-856d-b3641255e07c.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: AshiqurRah/ped#4

**Comment by EiffelLKF** [comment]
Good point! Will include it in future deployments!
